update cirlceci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,7 +19,6 @@ jobs:
 
     working_directory: ~/
     steps:
-      - checkout
       - run:
           name: Install dependencies
           working_directory: /
@@ -28,12 +27,23 @@ jobs:
             sudo apt-get upgrade -y
             apt-get install -y zip wget iputils-ping curl jq build-essential libssl-dev python python-pip python3 python3-pip file libgcrypt-dev git sudo build-essential libssl-dev awscli vim ffmpeg sqlite3
             pip3 install awscli --upgrade --user
-
       - run:
           name: Make Timelapse
           command: |
-            echo "Making Timelapse..."
-            echo "TARGET_AMI_TYPE=$TARGET_AMI_TYPE"
+            git clone https://$EAZE_AUTOMATION_GITHUB_CREDENTIAL@github.com/mathew-fleisch/timelapse-pipeline.git
+            cd timelapse-pipeline
+            mkdir -p files
+            cd scripts/processor
+            if ! [ -f "start.sh" ]; then
+              echo "Missing start.sh script"
+              exit 1
+            fi
+            echo "Make Timelapse..."
+            echo "TARGET_DATE=$TARGET_DATE"
+            echo "SOURCE_NAME=$SOURCE_NAME"
+            echo "SOURCE_BASE=$SOURCE_BASE"
+            ./start.sh --name ${SOURCE_NAME} --target-date ${TARGET_DATE} --source-base ${SOURCE_BASE} --target-dir /usr/timelapse/files --remove-night 1 --target-base ss3://eaze-timelapse/pipeline --sqlite-db timelapse.db
+
 
 
 # WORKFLOW - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
